apiVersion: apps/v1
kind: Deployment
metadata:
    name: cybertron-10-control-panel
    namespace: team-5
    labels:
        app: cybertron-10-control-panel
spec:
    replicas: 1
    selector:
        matchLabels:
            app: cybertron-10-control-panel
    template:
        metadata:
            labels:
                app: cybertron-10-control-panel
        spec:
            containers:
                - name: cybertron-10-control-panel
                  image: docker.mopalinski.com/cybertron-10-control-panel:latest
                  imagePullPolicy: Always
                  ports:
                      - containerPort: 80
                  env:
                      - name: FLAG
                        valueFrom:
                            secretKeyRef:
                                name: cybertron-10-control-panel
                                key: FLAG
                                optional: false
                      - name: ADMIN_PASSWORD
                        valueFrom:
                            secretKeyRef:
                                name: cybertron-10-control-panel
                                key: ADMIN_PASSWORD
                                optional: false
                      - name: USER_PASSWORD
                        valueFrom:
                            secretKeyRef:
                                name: cybertron-10-control-panel
                                key: USER_PASSWORD
                                optional: false
            nodeSelector:
                kubernetes.io/hostname: wn1523
            imagePullSecrets:
                - name: regcred
